// Curated list of popular companies college students apply to.
// Domain is the source of truth -> Clearbit logo URL is derived from it.
// Add to this list as we discover gaps in user usage.
export interface CompanyHint {
  name: string;
  domain: string; // primary marketing domain (no http://)
}

export const COMPANIES: CompanyHint[] = [
  // Tech (big)
  { name: 'Google', domain: 'google.com' },
  { name: 'Meta', domain: 'meta.com' },
  { name: 'Apple', domain: 'apple.com' },
  { name: 'Microsoft', domain: 'microsoft.com' },
  { name: 'Amazon', domain: 'amazon.com' },
  { name: 'Netflix', domain: 'netflix.com' },
  { name: 'Tesla', domain: 'tesla.com' },
  { name: 'Nvidia', domain: 'nvidia.com' },
  { name: 'Adobe', domain: 'adobe.com' },
  { name: 'Oracle', domain: 'oracle.com' },
  { name: 'Salesforce', domain: 'salesforce.com' },
  { name: 'IBM', domain: 'ibm.com' },
  { name: 'Intel', domain: 'intel.com' },
  { name: 'AMD', domain: 'amd.com' },
  { name: 'Qualcomm', domain: 'qualcomm.com' },
  { name: 'Cisco', domain: 'cisco.com' },
  { name: 'Uber', domain: 'uber.com' },
  { name: 'Lyft', domain: 'lyft.com' },
  { name: 'Airbnb', domain: 'airbnb.com' },
  { name: 'DoorDash', domain: 'doordash.com' },
  { name: 'Instacart', domain: 'instacart.com' },
  { name: 'Snap', domain: 'snap.com' },
  { name: 'Pinterest', domain: 'pinterest.com' },
  { name: 'Reddit', domain: 'reddit.com' },
  { name: 'X', domain: 'x.com' },
  { name: 'LinkedIn', domain: 'linkedin.com' },
  { name: 'PayPal', domain: 'paypal.com' },
  { name: 'Square', domain: 'squareup.com' },
  { name: 'Stripe', domain: 'stripe.com' },
  { name: 'Robinhood', domain: 'robinhood.com' },
  { name: 'Coinbase', domain: 'coinbase.com' },
  { name: 'Plaid', domain: 'plaid.com' },
  { name: 'Brex', domain: 'brex.com' },
  { name: 'Ramp', domain: 'ramp.com' },
  { name: 'Mercury', domain: 'mercury.com' },
  { name: 'Affirm', domain: 'affirm.com' },
  { name: 'Klarna', domain: 'klarna.com' },
  // Startups / scale-ups
  { name: 'OpenAI', domain: 'openai.com' },
  { name: 'Anthropic', domain: 'anthropic.com' },
  { name: 'Perplexity', domain: 'perplexity.ai' },
  { name: 'Cohere', domain: 'cohere.com' },
  { name: 'Hugging Face', domain: 'huggingface.co' },
  { name: 'Notion', domain: 'notion.so' },
  { name: 'Linear', domain: 'linear.app' },
  { name: 'Figma', domain: 'figma.com' },
  { name: 'Canva', domain: 'canva.com' },
  { name: 'Vercel', domain: 'vercel.com' },
  { name: 'Netlify', domain: 'netlify.com' },
  { name: 'Cloudflare', domain: 'cloudflare.com' },
  { name: 'Supabase', domain: 'supabase.com' },
  { name: 'MongoDB', domain: 'mongodb.com' },
  { name: 'Snowflake', domain: 'snowflake.com' },
  { name: 'Databricks', domain: 'databricks.com' },
  { name: 'Datadog', domain: 'datadoghq.com' },
  { name: 'Splunk', domain: 'splunk.com' },
  { name: 'GitLab', domain: 'gitlab.com' },
  { name: 'GitHub', domain: 'github.com' },
  { name: 'Atlassian', domain: 'atlassian.com' },
  { name: 'Asana', domain: 'asana.com' },
  { name: 'Slack', domain: 'slack.com' },
  { name: 'Zoom', domain: 'zoom.us' },
  { name: 'Twilio', domain: 'twilio.com' },
  { name: 'SendGrid', domain: 'sendgrid.com' },
  { name: 'Shopify', domain: 'shopify.com' },
  { name: 'Squarespace', domain: 'squarespace.com' },
  { name: 'Wix', domain: 'wix.com' },
  { name: 'Discord', domain: 'discord.com' },
  { name: 'Spotify', domain: 'spotify.com' },
  { name: 'TikTok', domain: 'tiktok.com' },
  { name: 'ByteDance', domain: 'bytedance.com' },
  { name: 'Roblox', domain: 'roblox.com' },
  { name: 'Unity', domain: 'unity.com' },
  { name: 'Epic Games', domain: 'epicgames.com' },
  { name: 'Riot Games', domain: 'riotgames.com' },
  { name: 'Activision', domain: 'activision.com' },
  { name: 'EA', domain: 'ea.com' },
  { name: 'Replit', domain: 'replit.com' },
  // Finance
  { name: 'Goldman Sachs', domain: 'goldmansachs.com' },
  { name: 'JP Morgan', domain: 'jpmorganchase.com' },
  { name: 'Morgan Stanley', domain: 'morganstanley.com' },
  { name: 'Citi', domain: 'citi.com' },
  { name: 'Bank of America', domain: 'bankofamerica.com' },
  { name: 'Wells Fargo', domain: 'wellsfargo.com' },
  { name: 'BlackRock', domain: 'blackrock.com' },
  { name: 'Bridgewater', domain: 'bridgewater.com' },
  { name: 'Citadel', domain: 'citadel.com' },
  { name: 'Two Sigma', domain: 'twosigma.com' },
  { name: 'Jane Street', domain: 'janestreet.com' },
  { name: 'Jump Trading', domain: 'jumptrading.com' },
  { name: 'Hudson River Trading', domain: 'hudsonrivertrading.com' },
  { name: 'DE Shaw', domain: 'deshaw.com' },
  // Consulting
  { name: 'McKinsey', domain: 'mckinsey.com' },
  { name: 'Bain', domain: 'bain.com' },
  { name: 'BCG', domain: 'bcg.com' },
  { name: 'Deloitte', domain: 'deloitte.com' },
  { name: 'PwC', domain: 'pwc.com' },
  { name: 'EY', domain: 'ey.com' },
  { name: 'KPMG', domain: 'kpmg.com' },
  { name: 'Accenture', domain: 'accenture.com' },
  // Aerospace / defense
  { name: 'Boeing', domain: 'boeing.com' },
  { name: 'Lockheed Martin', domain: 'lockheedmartin.com' },
  { name: 'SpaceX', domain: 'spacex.com' },
  { name: 'Anduril', domain: 'anduril.com' },
  { name: 'Palantir', domain: 'palantir.com' },
  { name: 'Scale AI', domain: 'scale.com' },
  { name: 'Rivian', domain: 'rivian.com' },
  { name: 'Northrop Grumman', domain: 'northropgrumman.com' },
  { name: 'Raytheon (RTX)', domain: 'rtx.com' },
  { name: 'General Dynamics', domain: 'gd.com' },
  { name: 'L3Harris', domain: 'l3harris.com' },
  { name: 'Textron', domain: 'textron.com' },

  // Enterprise software / SaaS
  { name: 'ServiceNow', domain: 'servicenow.com' },
  { name: 'Workday', domain: 'workday.com' },
  { name: 'SAP', domain: 'sap.com' },
  { name: 'VMware', domain: 'vmware.com' },
  { name: 'Dell', domain: 'dell.com' },
  { name: 'HP', domain: 'hp.com' },
  { name: 'HPE', domain: 'hpe.com' },
  { name: 'Lenovo', domain: 'lenovo.com' },
  { name: 'Autodesk', domain: 'autodesk.com' },
  { name: 'Intuit', domain: 'intuit.com' },
  { name: 'ADP', domain: 'adp.com' },
  { name: 'Paychex', domain: 'paychex.com' },
  { name: 'Zendesk', domain: 'zendesk.com' },
  { name: 'HubSpot', domain: 'hubspot.com' },
  { name: 'DocuSign', domain: 'docusign.com' },
  { name: 'Okta', domain: 'okta.com' },
  { name: 'CrowdStrike', domain: 'crowdstrike.com' },
  { name: 'Palo Alto Networks', domain: 'paloaltonetworks.com' },
  { name: 'Fortinet', domain: 'fortinet.com' },
  { name: 'Zscaler', domain: 'zscaler.com' },
  { name: 'SentinelOne', domain: 'sentinelone.com' },
  { name: 'Rapid7', domain: 'rapid7.com' },
  { name: 'Tenable', domain: 'tenable.com' },
  { name: 'Akamai', domain: 'akamai.com' },
  { name: 'Fastly', domain: 'fastly.com' },
  { name: 'DigitalOcean', domain: 'digitalocean.com' },
  { name: 'Confluent', domain: 'confluent.io' },
  { name: 'Elastic', domain: 'elastic.co' },
  { name: 'HashiCorp', domain: 'hashicorp.com' },
  { name: 'JFrog', domain: 'jfrog.com' },
  { name: 'PagerDuty', domain: 'pagerduty.com' },
  { name: 'New Relic', domain: 'newrelic.com' },
  { name: 'Sumo Logic', domain: 'sumologic.com' },
  { name: 'UiPath', domain: 'uipath.com' },
  { name: 'Box', domain: 'box.com' },
  { name: 'Dropbox', domain: 'dropbox.com' },
  { name: 'Evernote', domain: 'evernote.com' },
  { name: 'Miro', domain: 'miro.com' },
  { name: 'Airtable', domain: 'airtable.com' },
  { name: 'Monday.com', domain: 'monday.com' },
  { name: 'ClickUp', domain: 'clickup.com' },
  { name: 'Calendly', domain: 'calendly.com' },
  { name: 'Loom', domain: 'loom.com' },
  { name: 'Grammarly', domain: 'grammarly.com' },
  { name: 'Duolingo', domain: 'duolingo.com' },
  { name: 'Coursera', domain: 'coursera.org' },
  { name: 'Udemy', domain: 'udemy.com' },
  { name: 'Chegg', domain: 'chegg.com' },
  { name: 'Course Hero', domain: 'coursehero.com' },
  { name: 'Khan Academy', domain: 'khanacademy.org' },
  { name: 'Indeed', domain: 'indeed.com' },
  { name: 'Glassdoor', domain: 'glassdoor.com' },
  { name: 'ZipRecruiter', domain: 'ziprecruiter.com' },
  { name: 'Greenhouse', domain: 'greenhouse.io' },
  { name: 'Lever', domain: 'lever.co' },

  // AI / ML
  { name: 'Mistral AI', domain: 'mistral.ai' },
  { name: 'Stability AI', domain: 'stability.ai' },
  { name: 'Runway', domain: 'runwayml.com' },
  { name: 'ElevenLabs', domain: 'elevenlabs.io' },
  { name: 'Character.AI', domain: 'character.ai' },
  { name: 'Inflection AI', domain: 'inflection.ai' },
  { name: 'xAI', domain: 'x.ai' },
  { name: 'DeepMind', domain: 'deepmind.google' },
  { name: 'Waymo', domain: 'waymo.com' },
  { name: 'Cruise', domain: 'getcruise.com' },
  { name: 'Zoox', domain: 'zoox.com' },
  { name: 'Aurora Innovation', domain: 'aurora.tech' },

  // Fintech / payments / more finance
  { name: 'Visa', domain: 'visa.com' },
  { name: 'Mastercard', domain: 'mastercard.com' },
  { name: 'American Express', domain: 'americanexpress.com' },
  { name: 'Discover Financial', domain: 'discover.com' },
  { name: 'Fidelity Investments', domain: 'fidelity.com' },
  { name: 'Charles Schwab', domain: 'schwab.com' },
  { name: 'E*TRADE', domain: 'etrade.com' },
  { name: 'Vanguard', domain: 'vanguard.com' },
  { name: 'T. Rowe Price', domain: 'troweprice.com' },
  { name: 'State Street', domain: 'statestreet.com' },
  { name: 'Northern Trust', domain: 'northerntrust.com' },
  { name: 'Capital One', domain: 'capitalone.com' },
  { name: 'US Bank', domain: 'usbank.com' },
  { name: 'PNC', domain: 'pnc.com' },
  { name: 'Truist', domain: 'truist.com' },
  { name: 'Ally Financial', domain: 'ally.com' },
  { name: 'SoFi', domain: 'sofi.com' },
  { name: 'Chime', domain: 'chime.com' },
  { name: 'Wealthfront', domain: 'wealthfront.com' },
  { name: 'Betterment', domain: 'betterment.com' },
  { name: 'Marqeta', domain: 'marqeta.com' },
  { name: 'Adyen', domain: 'adyen.com' },
  { name: 'Wise', domain: 'wise.com' },
  { name: 'Revolut', domain: 'revolut.com' },
  { name: 'Nubank', domain: 'nubank.com.br' },
  { name: 'Block', domain: 'block.xyz' },
  { name: 'Cash App', domain: 'cash.app' },
  { name: 'Fiserv', domain: 'fiserv.com' },
  { name: 'FIS', domain: 'fisglobal.com' },
  { name: 'Global Payments', domain: 'globalpayments.com' },

  // Consulting / professional services (more)
  { name: 'Booz Allen Hamilton', domain: 'boozallen.com' },
  { name: 'Oliver Wyman', domain: 'oliverwyman.com' },
  { name: 'A.T. Kearney (Kearney)', domain: 'kearney.com' },
  { name: 'L.E.K. Consulting', domain: 'lek.com' },
  { name: 'Roland Berger', domain: 'rolandberger.com' },
  { name: 'Cognizant', domain: 'cognizant.com' },
  { name: 'Infosys', domain: 'infosys.com' },
  { name: 'Tata Consultancy Services', domain: 'tcs.com' },
  { name: 'Wipro', domain: 'wipro.com' },
  { name: 'Capgemini', domain: 'capgemini.com' },
  { name: 'Slalom', domain: 'slalom.com' },

  // Retail / e-commerce
  { name: 'Walmart', domain: 'walmart.com' },
  { name: 'Target', domain: 'target.com' },
  { name: 'Costco', domain: 'costco.com' },
  { name: 'Home Depot', domain: 'homedepot.com' },
  { name: "Lowe's", domain: 'lowes.com' },
  { name: 'Best Buy', domain: 'bestbuy.com' },
  { name: 'Kroger', domain: 'kroger.com' },
  { name: 'Albertsons', domain: 'albertsons.com' },
  { name: 'Nike', domain: 'nike.com' },
  { name: 'Adidas', domain: 'adidas.com' },
  { name: 'Under Armour', domain: 'underarmour.com' },
  { name: 'Lululemon', domain: 'lululemon.com' },
  { name: 'Gap Inc.', domain: 'gapinc.com' },
  { name: 'Ralph Lauren', domain: 'ralphlauren.com' },
  { name: 'Nordstrom', domain: 'nordstrom.com' },
  { name: "Macy's", domain: 'macys.com' },
  { name: 'TJX Companies', domain: 'tjx.com' },
  { name: 'Etsy', domain: 'etsy.com' },
  { name: 'Wayfair', domain: 'wayfair.com' },
  { name: 'Chewy', domain: 'chewy.com' },
  { name: 'eBay', domain: 'ebay.com' },
  { name: 'Alibaba', domain: 'alibaba.com' },
  { name: 'Sea Limited (Shopee)', domain: 'sea.com' },
  { name: 'MercadoLibre', domain: 'mercadolibre.com' },
  { name: 'Zalando', domain: 'zalando.com' },
  { name: 'ASOS', domain: 'asos.com' },

  // Healthcare / biotech / pharma
  { name: 'Johnson & Johnson', domain: 'jnj.com' },
  { name: 'Pfizer', domain: 'pfizer.com' },
  { name: 'Moderna', domain: 'modernatx.com' },
  { name: 'Merck', domain: 'merck.com' },
  { name: 'AbbVie', domain: 'abbvie.com' },
  { name: 'Bristol Myers Squibb', domain: 'bms.com' },
  { name: 'Eli Lilly', domain: 'lilly.com' },
  { name: 'AstraZeneca', domain: 'astrazeneca.com' },
  { name: 'GSK', domain: 'gsk.com' },
  { name: 'Novartis', domain: 'novartis.com' },
  { name: 'Roche', domain: 'roche.com' },
  { name: 'Sanofi', domain: 'sanofi.com' },
  { name: 'Amgen', domain: 'amgen.com' },
  { name: 'Gilead Sciences', domain: 'gilead.com' },
  { name: 'Regeneron', domain: 'regeneron.com' },
  { name: 'Vertex Pharmaceuticals', domain: 'vrtx.com' },
  { name: 'Illumina', domain: 'illumina.com' },
  { name: '23andMe', domain: '23andme.com' },
  { name: 'UnitedHealth Group', domain: 'unitedhealthgroup.com' },
  { name: 'CVS Health', domain: 'cvshealth.com' },
  { name: 'Elevance Health', domain: 'elevancehealth.com' },
  { name: 'Cigna', domain: 'cigna.com' },
  { name: 'Humana', domain: 'humana.com' },
  { name: 'Kaiser Permanente', domain: 'kaiserpermanente.org' },
  { name: 'HCA Healthcare', domain: 'hcahealthcare.com' },
  { name: 'Teladoc Health', domain: 'teladochealth.com' },
  { name: 'Oscar Health', domain: 'hioscar.com' },
  { name: 'Doximity', domain: 'doximity.com' },

  // Automotive
  { name: 'Ford', domain: 'ford.com' },
  { name: 'General Motors', domain: 'gm.com' },
  { name: 'Toyota', domain: 'toyota.com' },
  { name: 'Honda', domain: 'honda.com' },
  { name: 'Volkswagen', domain: 'vw.com' },
  { name: 'BMW', domain: 'bmw.com' },
  { name: 'Mercedes-Benz', domain: 'mercedes-benz.com' },
  { name: 'Stellantis', domain: 'stellantis.com' },
  { name: 'Nissan', domain: 'nissan-global.com' },
  { name: 'Hyundai', domain: 'hyundai.com' },
  { name: 'Kia', domain: 'kia.com' },
  { name: 'Volvo', domain: 'volvocars.com' },
  { name: 'Ferrari', domain: 'ferrari.com' },
  { name: 'Lucid Motors', domain: 'lucidmotors.com' },

  // Media / entertainment / streaming
  { name: 'Disney', domain: 'disney.com' },
  { name: 'Warner Bros. Discovery', domain: 'wbd.com' },
  { name: 'Comcast / NBCUniversal', domain: 'nbcuniversal.com' },
  { name: 'Paramount', domain: 'paramount.com' },
  { name: 'Sony Pictures', domain: 'sonypictures.com' },
  { name: 'Universal Music Group', domain: 'universalmusic.com' },
  { name: 'Warner Music Group', domain: 'wmg.com' },
  { name: 'Twitch', domain: 'twitch.tv' },
  { name: 'YouTube', domain: 'youtube.com' },
  { name: 'Vimeo', domain: 'vimeo.com' },
  { name: 'SoundCloud', domain: 'soundcloud.com' },
  { name: 'iHeartMedia', domain: 'iheartmedia.com' },

  // Telecom
  { name: 'AT&T', domain: 'att.com' },
  { name: 'Verizon', domain: 'verizon.com' },
  { name: 'T-Mobile', domain: 't-mobile.com' },
  { name: 'Charter Communications (Spectrum)', domain: 'charter.com' },
  { name: 'Dish Network', domain: 'dish.com' },
  { name: 'Vodafone', domain: 'vodafone.com' },

  // Airlines / travel / hospitality
  { name: 'Delta Air Lines', domain: 'delta.com' },
  { name: 'United Airlines', domain: 'united.com' },
  { name: 'American Airlines', domain: 'aa.com' },
  { name: 'Southwest Airlines', domain: 'southwest.com' },
  { name: 'JetBlue', domain: 'jetblue.com' },
  { name: 'Alaska Airlines', domain: 'alaskaair.com' },
  { name: 'Expedia Group', domain: 'expediagroup.com' },
  { name: 'Booking.com', domain: 'booking.com' },
  { name: 'TripAdvisor', domain: 'tripadvisor.com' },
  { name: 'Marriott', domain: 'marriott.com' },
  { name: 'Hilton', domain: 'hilton.com' },
  { name: 'Hyatt', domain: 'hyatt.com' },

  // Food & beverage
  { name: "McDonald's", domain: 'mcdonalds.com' },
  { name: 'Starbucks', domain: 'starbucks.com' },
  { name: 'Chipotle', domain: 'chipotle.com' },
  { name: 'Coca-Cola', domain: 'coca-colacompany.com' },
  { name: 'PepsiCo', domain: 'pepsico.com' },
  { name: 'Mondelez International', domain: 'mondelezinternational.com' },
  { name: 'Nestlé', domain: 'nestle.com' },
  { name: 'Kraft Heinz', domain: 'kraftheinzcompany.com' },
  { name: 'General Mills', domain: 'generalmills.com' },
  { name: "Kellogg's", domain: 'kelloggs.com' },
  { name: "Yum! Brands", domain: 'yum.com' },
  { name: "Domino's", domain: 'dominos.com' },
  { name: 'Chick-fil-A', domain: 'chick-fil-a.com' },

  // Insurance
  { name: 'State Farm', domain: 'statefarm.com' },
  { name: 'Allstate', domain: 'allstate.com' },
  { name: 'Progressive', domain: 'progressive.com' },
  { name: 'GEICO', domain: 'geico.com' },
  { name: 'Liberty Mutual', domain: 'libertymutual.com' },
  { name: 'The Travelers Companies', domain: 'travelers.com' },
  { name: 'MetLife', domain: 'metlife.com' },
  { name: 'Prudential Financial', domain: 'prudential.com' },
  { name: 'AIG', domain: 'aig.com' },
  { name: 'Nationwide', domain: 'nationwide.com' },
  { name: 'Farmers Insurance', domain: 'farmers.com' },

  // Energy
  { name: 'ExxonMobil', domain: 'exxonmobil.com' },
  { name: 'Chevron', domain: 'chevron.com' },
  { name: 'Shell', domain: 'shell.com' },
  { name: 'BP', domain: 'bp.com' },
  { name: 'ConocoPhillips', domain: 'conocophillips.com' },
  { name: 'NextEra Energy', domain: 'nexteraenergy.com' },
  { name: 'Duke Energy', domain: 'duke-energy.com' },

  // Logistics / delivery
  { name: 'FedEx', domain: 'fedex.com' },
  { name: 'UPS', domain: 'ups.com' },
  { name: 'DHL', domain: 'dhl.com' },
  { name: 'USPS', domain: 'usps.com' },
  { name: 'XPO Logistics', domain: 'xpo.com' },
  { name: 'C.H. Robinson', domain: 'chrobinson.com' },
  { name: 'Maersk', domain: 'maersk.com' },

  // Gaming (more)
  { name: 'Valve', domain: 'valvesoftware.com' },
  { name: 'Blizzard Entertainment', domain: 'blizzard.com' },
  { name: 'Take-Two Interactive', domain: 'take2games.com' },
  { name: 'Ubisoft', domain: 'ubisoft.com' },
  { name: 'Nintendo', domain: 'nintendo.com' },
  { name: 'Bandai Namco', domain: 'bandainamco.com' },
  { name: 'Sega', domain: 'sega.com' },
  { name: 'Zynga', domain: 'zynga.com' },
  { name: 'Niantic', domain: 'nianticlabs.com' },

  // Semiconductor (more)
  { name: 'ASML', domain: 'asml.com' },
  { name: 'TSMC', domain: 'tsmc.com' },
  { name: 'GlobalFoundries', domain: 'gf.com' },
  { name: 'Analog Devices', domain: 'analog.com' },
  { name: 'Marvell Technology', domain: 'marvell.com' },
  { name: 'Skyworks Solutions', domain: 'skyworksinc.com' },
  { name: 'Broadcom', domain: 'broadcom.com' },
  { name: 'Micron Technology', domain: 'micron.com' },
  { name: 'Western Digital', domain: 'westerndigital.com' },
  { name: 'Texas Instruments', domain: 'ti.com' },

  // Real estate / prop-tech
  { name: 'Zillow', domain: 'zillow.com' },
  { name: 'Redfin', domain: 'redfin.com' },
  { name: 'Compass', domain: 'compass.com' },
  { name: 'Opendoor', domain: 'opendoor.com' },
  { name: 'CBRE', domain: 'cbre.com' },
  { name: 'JLL', domain: 'jll.com' },

  // Government / national labs / public sector
  { name: 'NASA', domain: 'nasa.gov' },
  { name: 'MITRE', domain: 'mitre.org' },
  { name: 'DARPA', domain: 'darpa.mil' },
  { name: 'Sandia National Laboratories', domain: 'sandia.gov' },
  { name: 'Los Alamos National Laboratory', domain: 'lanl.gov' },
  { name: 'Lawrence Livermore National Laboratory', domain: 'llnl.gov' },
  { name: 'National Institutes of Health', domain: 'nih.gov' },
  { name: 'Federal Reserve', domain: 'federalreserve.gov' },

  // Non-profits / research orgs
  { name: 'Gates Foundation', domain: 'gatesfoundation.org' },
  { name: 'Wikimedia Foundation', domain: 'wikimediafoundation.org' },
  { name: 'Mozilla', domain: 'mozilla.org' },
  { name: 'American Red Cross', domain: 'redcross.org' },
  { name: 'World Bank', domain: 'worldbank.org' },
  { name: 'International Monetary Fund', domain: 'imf.org' },
];

/**
 * Free, no-key logo URL. Google's favicon service returns up to 128px — much
 * crisper than DuckDuckGo's 16px .ico. Use `logoFallbackUrl` as onError source.
 */
export function logoUrl(domain: string, size = 128) {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=${size}`;
}

/** Lower-res but very reliable fallback if Google has no icon for a domain. */
export function logoFallbackUrl(domain: string) {
  return `https://icons.duckduckgo.com/ip3/${domain}.ico`;
}

/** Type-ahead match: prefix first, then contains. Returns up to 6. */
export function searchCompanies(query: string, limit = 6): CompanyHint[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const prefix: CompanyHint[] = [];
  const contains: CompanyHint[] = [];
  for (const c of COMPANIES) {
    const n = c.name.toLowerCase();
    if (n === q || n.startsWith(q)) prefix.push(c);
    else if (n.includes(q)) contains.push(c);
    if (prefix.length >= limit) break;
  }
  return [...prefix, ...contains].slice(0, limit);
}
